{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-backend-rules
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: amazon-backend-alerts
    rules:
    - alert: BackendHighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}", pod=~"{{ .Release.Name }}-backend-.*"}[2m])) by (pod) > 0.8
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High CPU Usage on Backend Pod: {{`{{ $labels.pod }}`}}"
        description: "Pod {{`{{ $labels.pod }}`}} is using more than 80% CPU for the last 2 minutes."
    - alert: BackendHighMemoryUsage
      expr: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}", pod=~"{{ .Release.Name }}-backend-.*"}) by (pod) / sum(kube_pod_container_resource_limits{namespace="{{ .Release.Namespace }}", pod=~"{{ .Release.Name }}-backend-.*", resource="memory"}) by (pod) > 0.85
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High Memory Usage on Backend Pod: {{`{{ $labels.pod }}`}}"
        description: "Pod {{`{{ $labels.pod }}`}} is using more than 85% of its Memory limit for the last 2 minutes."
{{- end }}
