apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-backend
  labels:
    app: amazon-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon-backend
  template:
    metadata:
      labels:
        app: amazon-backend
    spec:
      containers:
        - name: amazon-backend
          # User's Account ID: 406312601212
          image: 406312601212.dkr.ecr.us-east-1.amazonaws.com/amazon-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_password
            - name: SPRING_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: redis_host
            - name: SPRING_REDIS_PORT
              value: "6379"
            # RabbitMQ Config
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: rabbitmq_host
            - name: SPRING_RABBITMQ_PORT
              value: "5671"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: rabbitmq_username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: rabbitmq_password
            - name: SPRING_RABBITMQ_SSL_ENABLED
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-backend
spec:
  selector:
    app: amazon-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Changed from ClusterIP to allow Public Access (Client-Side Fetch)
