apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-backend
spec:
  # High Availability: Run 2 copies of the pod
  replicas: 2
  selector:
    matchLabels:
      app: amazon-backend
  template:
    metadata:
      labels:
        app: amazon-backend
    spec:
      containers:
      - name: backend
        image: amazon-backend:latest
        imagePullPolicy: IfNotPresent # Use local image if available
        ports:
        - containerPort: 8080
        # Inject Database Connection String
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://amazon-mysql:3306/amazonlike_db"
