apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  # YOU MUST REPLACE THESE VALUES WITH YOUR TERRAFORM OUTPUTS
  db_url: "jdbc:mysql://amazon-db.cij2uokqq8ri.us-east-1.rds.amazonaws.com:3306/amazon_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
  db_username: "admin"
  db_password: "~D$RZqPrp$AbDmDLXj4ikDesA0W-" # Retrieved from AWS Secrets Manager
  redis_host: "master.amazon-redis-rep-group.gtvmwh.use1.cache.amazonaws.com"
  # RabbitMQ
  rabbitmq_host: "b-c040d66d-092a-43b4-a264-4d68b0435e84.mq.us-east-1.amazonaws.com"
  rabbitmq_username: "admin"
  rabbitmq_password: "Q7TiVm1LcLpQvrTx"
