apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  # YOU MUST REPLACE THESE VALUES WITH YOUR TERRAFORM OUTPUTS
  db_url: "jdbc:mysql://<REPLACE_WITH_RDS_ENDPOINT>:3306/amazon_db?useSSL=false&allowPublicKeyRetrieval=true"
  db_username: "admin"
  db_password: "password123" # Matches variables.tf default
  redis_host: "<REPLACE_WITH_REDIS_ENDPOINT>"
