apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  # YOU MUST REPLACE THESE VALUES WITH YOUR TERRAFORM OUTPUTS
  db_url: "jdbc:mysql://<RDS_ENDPOINT>:3306/amazon_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
  db_username: "admin"
  db_password: "<RDS_PASSWORD>"
  redis_host: "<REDIS_ENDPOINT>"
  # RabbitMQ
  rabbitmq_host: "<RABBITMQ_HOST>"
  rabbitmq_username: "admin"
  rabbitmq_password: "<RABBITMQ_PASSWORD>"
