apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  db_url: "<RDS_ENDPOINT>"
  db_username: "admin"
  db_password: "<RDS_PASSWORD>"
  redis_host: "<REDIS_ENDPOINT>"
  rabbitmq_host: "<MQ_ENDPOINT>"
  rabbitmq_username: "admin"
  rabbitmq_password: "<MQ_PASSWORD>"
