apiVersion: v1
kind: Service
metadata:
  name: grafana-bridge
  namespace: default
spec:
  type: ExternalName
  externalName: kube-prom-stack-grafana.monitoring.svc.cluster.local
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
