apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amazon-frontend-monitor
  namespace: devsecops
  labels:
    app: amazon-frontend
    release: prometheus # Common label for Prometheus Operator to select monitors
spec:
  selector:
    matchLabels:
      app: amazon-frontend
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - devsecops
