apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cost-exporter
  namespace: devsecops
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: cost-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - devsecops
