# Elasticsearch & Kibana Helm Values
# Repo: https://helm.elastic.co

# ===========================
# Elasticsearch
# ===========================
replicas: 1 # Single node for cost saving (Use 3 for prod)
minimumMasterNodes: 1

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Persistence (Save logs to disk)
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi

# ===========================
# Kibana
# ===========================
kibana:
  service:
    type: LoadBalancer # Expose UI to the internet

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
