# Vault Helm Chart Values
# Repo: https://helm.releases.hashicorp.com

global:
  enabled: true
  tlsDisable: true

server:
  # Run in "Desvelopment" mode (in-memory storage) for learning.
  # For Prod, set this to false and configure a Consul backend.
  dev:
    enabled: true
  
  # Enable the Vault UI
  ui:
    enabled: true
    serviceType: "LoadBalancer"

  # High Availability Configuration (Raft Consensus)
  ha:
    enabled: false # Set to true for Production
    replicas: 3
    raft:
      enabled: true

# Injector Sidecar Configuration
injector:
  enabled: true
  # This automatically injects secrets into pods with specific annotations
