apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/attach", "pods/log", "secrets", "configmaps", "services", "persistentvolumeclaims", "nodes"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-runner
roleRef:
  kind: ClusterRole
  name: gitlab-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |
    concurrent = 4
    check_interval = 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      serviceAccountName: gitlab-runner
      containers:
        - name: gitlab-runner
          image: gitlab/gitlab-runner:alpine
          env:
            - name: CI_SERVER_URL
              value: "https://gitlab.com/"
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-runner-secret
                  key: registration-token
          command: ["/bin/bash", "-c"]
          args:
            - |
              cp /config-template/config.toml /etc/gitlab-runner/config.toml
              
              # register command
              gitlab-runner register \
                --non-interactive \
                --url https://gitlab.com/ \
                --token "$REGISTRATION_TOKEN" \
                --executor kubernetes \
                --tag-list amazon-clone \
                --locked=false \
                --kubernetes-namespace "gitlab-runner" \
                --kubernetes-service-account "gitlab-runner" && \
              
              # Inject Volume Mount ONLY if register succeeded
              cat <<EOF >> /etc/gitlab-runner/config.toml
              
              [[runners.kubernetes.volumes.empty_dir]]
                name = "zap-wrk"
                mount_path = "/zap/wrk"
                medium = "Memory"
              EOF

              gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner
          volumeMounts:
            - name: config-template
              mountPath: "/config-template"
            - name: runner-data
              mountPath: "/etc/gitlab-runner"
      volumes:
        - name: config-template
          configMap:
            name: gitlab-runner-config
        - name: runner-data
          emptyDir: {}
