---
- name: Configure App Server
  hosts: all
  become: yes # Run as root (sudo)
  tasks:
    # 1. Install Docker Engine
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # 2. Install Docker Compose
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    # 3. Deploy Code
    - name: Copy App Files
      copy:
        src: ../../ # Copy file from host machine to target server
        dest: /opt/amazonlikeapp

    # 4. Start Application
    - name: Start App
      command: docker-compose up -d
      args:
        chdir: /opt/amazonlikeapp
