name: Deploy App to EKS

on:
  workflow_dispatch: # Manual trigger for safety
  push:
    branches: [ "phase-6a-githubactions", "phase-10-features" ]
  release:
    types: [published]

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout
  issues: write   # Required for ZAP to create issues for findings

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name amazon-cluster --region us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy using Script
        # Assumes runner has docker, kubectl, envsubst
        env:
          AWS_ACCOUNT_ID: ${{ steps.login-ecr.outputs.registry }} # Use registry ID from login step
          DOMAIN_NAME: devcloudproject.com
        run: |
            chmod +x ops/scripts/deploy_k8s.sh
            ./ops/scripts/deploy_k8s.sh

  dast-scan:
    name: DAST (OWASP ZAP)
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.devcloudproject.com'
          cmd_options: '-a' # Include alpha rules
